#!/bin/bash
#
# Copyright 2012-2017 Chef Software, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

PATH=/opt/gitlab/bin:/opt/gitlab/embedded/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin

ulimit -S  -c 0
ulimit -S  -d unlimited
ulimit -S  -e 0
ulimit -S  -f unlimited
#ulimit -S  -i 62793
ulimit -S  -l 64
ulimit -S  -m unlimited
# WARNING: Increasing the global file descriptor limit increases RAM
# consumption on startup dramatically!
ulimit -S  -n 50000
ulimit -S  -q 819200
ulimit -S  -r 0
ulimit -S  -s 10240
ulimit -S  -t unlimited
#ulimit -S  -u unlimited
ulimit -S  -v unlimited
ulimit -S  -x unlimited

umask 022

exec env - PATH=$PATH \
runsvdir -P /opt/gitlab/service 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
