#!/bin/sh

if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    echo "Setting runtime User ... "

    #echo "${USER_NAME:-git}:x:$(id -u):0:${USER_NAME:-git} user:${HOME}:/bin/sh" >> /etc/passwd

    sed 's@git:x:1001:@git:x:'$(id -u)':@g' /etc/passwd.template > /etc/passwd
    sed -i 's/ID_USER/'"$(id -u)"'/g' /assets/gitlab.rb

  fi
fi
exec "$@"
