#!/bin/bash

set -x

# chown_if_exists
# input: matches `chown` command, see `man chown`
# Simply, this checks that the file you're trying to chown actually exists
# before making the chown call. DRY'ing the rest of this script's checks.
chown_if_exists()
{
	# the last argument of chown is the file or path
	path="${@:${#@}}"
	if [ -e "$path" ]; then
		chown $@
	else
		echo "skipping, path does not exist: $path"
	fi
}

chown_if_exists -R 1001:0 /var/opt/gitlab
chown_if_exists -R 1001:0 /var/log/gitlab
